/**
 * Form Fields Configuration
 *
 * Auto-generated form field definitions.
 * Each field includes type, validation, and display properties.
 */

export default [
	{
		name: "blog_category_id",
		label: "Enter Blog Category Id",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "title",
		label: "Enter Title",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "description",
		label: "Enter Description",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "content",
		label: "Enter Content",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "reading_time",
		label: "Enter Reading Time",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "tags",
		label: "Enter Tags",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "publish_date",
		label: "Enter Publish Date",
		type: "datetime-local",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "writer",
		label: "Enter Writer",
		type: "number",
		step: "1",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "thumbnail_image",
		label: "Enter Thumbnail Image",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "images",
		label: "Enter Images",
		type: "textarea",
		rows: 4,
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "blog_type",
		label: "Enter Blog Type",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "url",
		label: "Enter Url",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "show_top",
		label: "Enter Show Top",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "contributors",
		label: "Enter Contributors",
		type: "textarea",
		rows: 6,
		placeholder: "Enter valid JSON data",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "video_link",
		label: "Enter Video Link",
		type: "text",
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_featured",
		label: "Enter Is Featured",
		type: "select",
		multiple: false,
		data_list: [
			{
				label: "Yes",
				value: "1",
			},
			{
				label: "No",
				value: "0",
			},
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
	{
		name: "is_published",
		label: "Enter Is Published",
		type: "select",
		multiple: false,
		data_list: [
			{
				label: "Yes",
				value: "1",
			},
			{
				label: "No",
				value: "0",
			},
		],
		value: "",
		is_visible: true,
		class: "col-md-6",
	},
];
